sudo: false
language: node_js
node_js:
  - "4"
before_script:
  - npm install -g npm@3
  - npm install -g grunt-cli
  - npm install -g bower
  - bower install
script:
  - npm run-script test-on-travis
